import {DEVICE_NAME, USER_AGENT} from "./constants.js";
import fetch from "node-fetch";
import {Agent} from "https";


export async function getProfile({accessToken, clientVendorID, proxyAgent = undefined}: {
    accessToken: string,
    clientVendorID: string,
    proxyAgent: Agent | undefined
}) {
    const resp = await fetch("https://oauth.reddit.com/api/v1/me?raw_json=1&raw_json=1&feature=link_preview&sr_detail=true&expand_srs=true&from_detail=true&api_type=json&always_show_media=1", {
        method: "GET",
        headers: {
            "x-reddit-retry": "attempt=0, max=3, algo=full-jitter",
            "x-reddit-compression": "1",
            "x-reddit-qos": "down-rate-mbps=3.200",
            "x-reddit-media-codecs": "available-codecs=",
            "client-vendor-id": clientVendorID,
            "x-reddit-device-id": clientVendorID,
            "user-agent": USER_AGENT,
            "x-dev-ad-id": "",
            "device-name": DEVICE_NAME,
            "x-reddit-dpr": "2.0",
            "x-reddit-width": "720",
            "authorization": `Bearer ${accessToken}`,
            "accept-language": "en,en;q=0.9"
        },
        agent: proxyAgent,
    });

    return (await resp.json()) as ProfileResponse;
}

interface ProfileResponse {
    // is_employee: false,
    // seen_layout_switch: false,
    // has_visited_new_profile: false,
    // pref_no_profanity: true,
    // has_external_account: false,
    // pref_geopopular: '',
    // seen_redesign_modal: false,
    // pref_show_trending: true,
    // subreddit: {
    //     default_set: true,
    //     user_is_contributor: false,
    //     banner_img: '',
    //     restrict_posting: true,
    //     user_is_banned: false,
    //     free_form_reports: true,
    //     community_icon: null,
    //     show_media: true,
    //     icon_color: '#FF99AA',
    //     user_is_muted: null,
    //     display_name: 'u_redacted_name_here',
    //     header_img: null,
    //     title: '',
    //     coins: 0,
    //     previous_names: [],
    //     over_18: false,
    //     icon_size: [256, 256],
    //     primary_color: '',
    //     icon_img: 'https://www.redditstatic.com/avatars/defaults/v2/avatar_default_0.png',
    //     description: '',
    //     allowed_media_in_comments: [],
    //     submit_link_label: '',
    //     header_size: null,
    //     restrict_commenting: false,
    //     subscribers: 0,
    //     submit_text_label: '',
    //     is_default_icon: true,
    //     link_flair_position: '',
    //     display_name_prefixed: 'u/redacted_name_here',
    //     key_color: '',
    //     name: 't5_8kmd13',
    //     is_default_banner: true,
    //     url: '/user/redacted_name_here/',
    //     quarantine: false,
    //     banner_size: null,
    //     user_is_moderator: true,
    //     accept_followers: true,
    //     public_description: '',
    //     link_flair_enabled: false,
    //     disable_contributor_requests: false,
    //     subreddit_type: 'user',
    //     user_is_subscriber: false
    // },
    // pref_show_presence: true,
    // snoovatar_img: '',
    // snoovatar_size: null,
    // gold_expiration: null,
    // has_gold_subscription: false,
    // is_sponsor: false,
    // num_friends: 0,
    // features: {
    //     modmail_harassment_filter: true,
    //     mod_service_mute_writes: true,
    //     promoted_trend_blanks: true,
    //     show_amp_link: true,
    //     chat: true,
    //     is_email_permission_required: false,
    //     mod_awards: true,
    //     mweb_xpromo_revamp_v3: { owner: 'growth', variant: 'treatment_4', experiment_id: 480 },
    //     mweb_xpromo_revamp_v2: { owner: 'growth', variant: 'control_1', experiment_id: 457 },
    //     awards_on_streams: true,
    //     mweb_xpromo_modal_listing_click_daily_dismissible_ios: true,
    //     chat_subreddit: true,
    //     cookie_consent_banner: true,
    //     modlog_copyright_removal: true,
    //     do_not_track: true,
    //     images_in_comments: true,
    //     mod_service_mute_reads: true,
    //     chat_user_settings: true,
    //     use_pref_account_deployment: true,
    //     mweb_xpromo_interstitial_comments_ios: true,
    //     mweb_xpromo_modal_listing_click_daily_dismissible_android: true,
    //     premium_subscriptions_table: true,
    //     mweb_xpromo_interstitial_comments_android: true,
    //     crowd_control_for_post: true,
    //     mweb_sharing_web_share_api: { owner: 'growth', variant: 'control_1', experiment_id: 314 },
    //     chat_group_rollout: true,
    //     resized_styles_images: true,
    //     noreferrer_to_noopener: true,
    //     expensive_coins_package: true
    // },
    // can_edit_name: false,
    // verified: true,
    // new_modmail_exists: null,
    // pref_autoplay: true,
    // coins: 0,
    // has_paypal_subscription: false,
    // has_subscribed_to_premium: false,
    // id: 'd5ml5lq2s',
    // has_stripe_subscription: false,
    // oauth_client_id: 'ohXpoqrZYub1kg',
    // can_create_subreddit: true,
    // over_18: false,
    // is_gold: false,
    // is_mod: false,
    // awarder_karma: 0,
    // suspension_expiration_utc: null,
    // has_verified_email: false,
    // is_suspended: false,
    // pref_video_autoplay: true,
    // in_chat: true,
    // has_android_subscription: false,
    // in_redesign_beta: true,
    // icon_img: 'https://www.redditstatic.com/avatars/defaults/v2/avatar_default_0.png',
    // has_mod_mail: false,
    // pref_nightmode: false,
    // unverified_email: 'redacted_name_here@example.com',
    // hide_from_robots: false,
    // password_set: true,
    // link_karma: 1,
    // force_password_reset: false,
    // total_karma: 1,
    // seen_give_award_tooltip: false,
    // inbox_count: 0,
    // seen_premium_adblock_modal: false,
    // pref_top_karma_subreddits: true,
    // has_mail: false,
    // pref_show_snoovatar: false,
    // name: 'redacted_name_here',
    // pref_clickgadget: 5,
    // created: 1686444719,
    // gold_creddits: 0,
    // created_utc: 1686444719,
    // has_ios_subscription: false,
    // pref_show_twitter: false,
    // in_beta: false,
    // comment_karma: 0,
    // accept_followers: true,
    // has_subscribed: false,
    // seen_subreddit_chat_ftux: false,
    // linked_identities: [],
    // awardee_karma: 0,
}